export { default as ShopItems } from './shared/ShopItems'
export { default as Footer } from './shared/Footer'
export { default as Header } from './shared/Header'
export { default as Announcement } from './shared/Announcement'
export { default as ViewProduct } from './home/ViewProduct'
export { default as NewProduct } from './home/NewProduct'
export { default as Home } from '../pages/Home'
export { default as ProductCategory } from '../pages/ProductCategory'
export { default as ProductDetail } from '../pages/ProductDetail'
export { default as AddToCart } from '../components/product-detail/AddToCart'
export { default as Cart } from './shared/Cart'
export { default as Menu } from './shared/Menu'
export { default as Recommended } from '../components/product-detail/Recommended'
export { default as InTheBox } from '../components/product-detail/InTheBox'
export { default as Features } from '../components/product-detail/Features'
export { default as ImageGallery } from '../components/product-detail/ImageGallery'
// export { default as CheckoutForm } from '../pages/checkout/CheckoutForm'
export { default as Layout } from '../components/Layout'
